before:
  hooks:
    - go mod vendor
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    main: ./cmd/terjang/main.go
    mod_timestamp: '{{ .CommitTimestamp }}'
    ldflags:
      - -X main.version={{.Version}} -X main.commit={{.Commit}}
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "dev"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - Merge pull request
      - Merge branch
archives:
  - format_overrides:
    - goos: windows
      format: zip
dockers:
- image_templates:
  - 'andylibrian/terjang:{{ .Version }}-amd64'
  - 'andylibrian/terjang:latest'
  - 'ghcr.io/andylibrian/terjang:{{ .Version }}-amd64'
  - 'ghcr.io/andylibrian/terjang:latest'
  dockerfile: Dockerfile
  build_flag_templates:
  - "--pull"
  - "--label=org.opencontainers.image.created={{.Date}}"
  - "--label=org.opencontainers.image.name={{.ProjectName}}"
  - "--label=org.opencontainers.image.revision={{.FullCommit}}"
  - "--label=org.opencontainers.image.version={{.Version}}"
  - "--label=org.opencontainers.image.source={{.GitURL}}"
  - "--platform=linux/amd64"
